[build-system]
requires = [
    'setuptools>=40.8.0',
    'Django>=5.0,<6.0',
    'djangorestframework>=3.14.0',
    'django-cors-headers>=4.3.0',
    'django-extensions>=3.2.0',
    'djangorestframework-simplejwt>=5.3.0'
]
build-backend = 'setuptools.build_meta'