[build-system]
requires = [
    'setuptools>=40.8.0',
    'Django==5.0.6',
    'django-cors-headers==4.3.1',
    'django-extensions==3.2.3',
    'djangorestframework==3.15.1',
    'djangorestframework-simplejwt==5.3.1'
]
build-backend = 'setuptools.build_meta'